### ISSUE TITLE
Have you tried Rocket?

### ISSUE THREAD

**Issue by devlato** [victorhqc/simple-page#1]
Hey mate, have you tried [Rocket](https://rocket.rs/)? 🙂

<img src="https://user-images.githubusercontent.com/1210210/61178394-8c5ba200-a62f-11e9-8613-0af3f2b4e61e.jpeg" width="128" height="128" />

**Comment by victorhqc** [comment]
I haven't, what do you think about it?

**Comment by devlato** [comment]
@victorhqc pretty nice, their ~~buggest~~ biggest disadvantage is relying on nightly builds

**Comment by victorhqc** [comment]
hahaha I see, then I don't plan to use it until they go and use stable builds :)
